name: tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - uses: nrwl/nx-set-shas@v4
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm

      - uses: nrwl/nx-set-shas@v4
      - run: npm ci
      # TODO: re-enable when it stops erroring constantly about package.json
      # - run: npx nx format:check
      - run: npx nx affected:test --ci --code-coverage

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm

      - uses: nrwl/nx-set-shas@v4
      - run: npm ci
      - run: npx nx affected:build
